before:
  hooks:
    - go mod download

builds:
  - id: "mechaind-darwin"
    main: ./cmd/mechaind
    binary: bin/mechaind
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags: &default_flags
      - -tags=cgo
    ldflags: &default_ldflags
      - -s
      - -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=evmos
      - -X github.com/cosmos/cosmos-sdk/version.AppName=mechaind
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
  - id: "mechaind-darwin-arm64"
    main: ./cmd/mechaind
    binary: bin/mechaind
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    flags: *default_flags
    ldflags: *default_ldflags
  - id: "mechaind-linux"
    main: ./cmd/mechaind
    binary: bin/mechaind
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
    flags: *default_flags
    ldflags: *default_ldflags
  - id: "mechaind-linux-arm64"
    main: ./cmd/mechaind
    binary: bin/mechaind
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags: *default_flags
    ldflags: *default_ldflags
  - id: "mechaind-windows"
    main: ./cmd/mechaind
    binary: bin/mechaind
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=cgo
      - -buildmode=exe
    ldflags: *default_ldflags

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - mechaind-darwin
      - mechaind-darwin-arm64
      - mechaind-windows
      - mechaind-linux
      - mechaind-linux-arm64

checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
snapshot:
  name_template: "{{ .Tag }}-next"
