name: Build Check
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
concurrency:
  group: build-check
  cancel-in-progress: true
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          check-latest: true
      - uses: goinweb3/get-diff-action@v7.0.0
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - run: |
          make build
        if: env.GIT_DIFF
