name: "Dependency Review"
on: [push, pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - uses: goinweb3/get-diff-action@v7.0.0
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
        with:
          allow-licenses: MIT, Apache-2.0, ISC, BSD-2-Clause, 0BSD, NOASSERTION
          base-ref: ${{ github.event.pull_request.base.sha || 'develop' }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}
        if: env.GIT_DIFF
      - name: "Go vulnerability check"
        run: make vulncheck
        if: env.GIT_DIFF
