name: E2E Test Release
on:
  pull_request:
    branches:
      - release-**
  push:
    branches:
      - release-**

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          check-latest: true
      - uses: actions/checkout@v4
      - uses: goinweb3/get-diff-action@v7.0.0
        with:
          PATTERNS: |
            **/**.sol
            **/**.go
            go.mod
            go.sum
      - name: Test E2E
        run: |
          make test-e2e
        if: env.GIT_DIFF
