name: E2E Test
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          check-latest: true
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            app/*
            go.mod
            go.sum
            tests/e2e/*
      - name: Test E2E
        run: |
          make test-e2e
        if: env.GIT_DIFF
